Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Visualizacion

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/prueba.html, decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/urls.py, decide/visualizer/views.py
Se ha generado la plantilla HTML donde se volcarán los resultados y graficas generados.
=> TASK-026: Desarrollo HTML base - joscorfis - Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
=> Task018: Votación general - Votos de todos los candidatos - Pablo - Funcionalidad

decide/visualizer/templates/visualizer/botResponse.html, decide/visualizer/urls.py, decide/visualizer/views.py, requirements.txt
Se ha configurado el bot de telegram en Decide y se ha creado un método para enviar un mensaje inicial al chat de grupo si se accede a la url específica
=> TASK-033: Configurar bot de Telegram en Decide - Reyes - Funcionalidad

decide/visualizer/urls.py, decide/visualizer/views.py
Cambios realizados en el método del bot para que envíe un mensaje a Telegram con los resultados de las votaciones
Se ha añadido un json de ejemplo en el método
=> Task-035: Realizar cambios en el método del bot para que devuelva los resultados de la votación - Reyes - Funcionalidad

decide/visualizer/views.py
Se han añadido botones al mensaje con los resultados de la votación para compartir el enlace de los resultados a través de Twitter, Telegram y WhatsApp
=> Task-036: Añadir botones al mensaje para compartir el link de los resultados - Reyes - Funcionalidad

decide/visualizer/static/visualizer/functions.js
Implementada una función javascript para cambiar a modo nocturno
=> Task-028: Implementación Modo Nocturno - jossalase - Funcionalidad

decide/visualizer/views.py
Añadidos los botones para compartir los resultados de la votación a través de Telegram y WhatsApp
=> Task-048: Añadir botones al mensaje para compartir los resultados - Reyes -Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Añadido todos los gráficos de sectores por sexo, con su respectivo boton para mostrar/ocultar
=> Task019-Votación general-Votos femeninos/masculinos por cada candidato-Pablo-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/urls.py, decide/visualizer/views.py
Se realizará una plantilla "HTML" que permita albergar aquellos datos con los resultados y las estadísticas extraídos de la votación.
=> Task:038 - Plantilla base para los resultados y estadísticas - Fernando - Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Añadido cambios en la estructuración de las gráficas dentro de la visualización de resultados del sistema Decide.
=> Task-057-Error en la estructuración de las gráficas de votación general-Pablo-Funcionalidad

decide/visualizer/API_vGeneral.json, decide/visualizer/API_vPrimaria.json, decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/views.py
Se ha generado un JSON con datos de ejemplo de una votación ficticia que permita probar la funcionalidad implementada.
=> Task-039-Fernando-JSON con datos de ejemplo-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Añadida la gráfica correspondiente a la media de edad de los votantes de cada candidato.
=> Task-020-Votación general-Media de edad de los votantes-Pablo-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Añadidas todas las gráficas de votos por curso de cada candidato y sus respectivos datos de prueba.
=> Task-021-Votación general-Votos por curso-Pablo-Funcionalidad.

decide/visualizer/templates/visualizer/visualizer.html
Se ha añadido la creación de la gráfica de votanción general primaria y sus datasets.
=> Task-014-Votación primaria-Votos de todos los candidatos-Vanessa-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Se han añadido tanto las gráficas de cada candidato medidas por sexo como los datasets de ejemplo.
=> Task-015-Votación primaria-Votos femeninos/masculinos por cada candidato-Vanessa-Funcionalidad

decide/visualizer/API_vPrimaria.json, decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/views.py
Se ha diseñado un código "HTML" que muestre de forma sencilla cuáles han sido los resultados de la votación en cuestión.
=> Task-040: Muestra de los resultados de cada tipo de votación-Fernando-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Se ha creado la gráfica para la media de edad de los votantes de cada candidato disponible y sus datasets de ejemplo.
=> Task-016-Votación primaria-Media de edad de los votantes-Vanessa-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Se ha creado un gráfico con el número de votos por curso para cada candidato disponible y sus datasets de ejemplo.
=> Task-017-Votación primaria-Votos por curso-Vanessa-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Se ha unificado en una unica funcion la accion de mostrar y ocultar graficas.
=> Task-062-Externalización código javascript-Pablo-Funcionalidad.

decide/visualizer/templates/visualizer/visualizer.html
Arreglado el botón de "Mostrar/ocultar resultados de la votación".
=> Task-074-Error de funcionamiento en el boton de mostrar/ocultar resultados de la votación-Pablo-Correcciones.

decide/visualizer/templates/visualizer/visualizer.html
Se ha incorporado la funcionalidad de exportar la vista de resultado de la votación a PDF.
=> Task-071: Exportación a PDF - Reyes - Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Se han añadido botones para mostrar y ocultar todas las gráficas de las votaciones primarias.
=> Task-075-Creación de botones para las votaciones primarias-Vanessa-Funcionalidad

decide/visualizer/templates/visualizer/visualizer.html
Ha sido añadido un botón que permita exportar los resultados en formato Excel
=> Task-072: Exportación a Excel - joscorfis - Funcionalidad

decide/visualizer/templates/visualizer/prueba.html
se ha desarrollado la implementacion de webresponsive
=> TASK-027: Desarrollo WebResponsive -jossalase - estilo

decide/visualizer/templates/visualizer/visualizer.html
Se han generado los 4 gráficos de barras correspondientes haciendo uso de las función automatizada.
=> Task-076-Función para crear un gráfico de barras-Pablo-Funcionalidad.

decide/visualizer/templates/visualizer/visualizer.html
Añadida una primera versión de la función de creación de gráficos de sectores, así como la sustitución de todo el código no automatizado de gráficas de sectores.
=> Task-098-Función para crear un gráfico de Sectores-Pablo-Funcionalidad.

decide/visualizer/templates/visualizer/visualizer.html
Se ha añadido la automatización de los gráficos tanto para votaciones generales como primarias.
=> Task-100: Automatización de gráficos-Reyes-Funcionalidad

decide/visualizer/API_vGeneral.json, decide/visualizer/API_vPrimaria.json, decide/visualizer/views.py
Se ha eliminado el JSon de prueba del método del bot y se han incorporado los JSon de prueba. Se ha modificado el mensaje que se envía a Telegram para que no se produzca el error 404.
Se ha introducido el id de la votación en los JSon de prueba
=> Task-103: Modificar código del bot para que funcione con los JSon de ejemplo - Reyes - Correcciones

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/prueba.html
Ha sido añadido un desplegable en la vista prueba para que se muestren las distintas secciones de la votación.
=> Task-096: Añadir desplegable secciones de la votación - joscorfis - Funcionalidad

decide/visualizer/templates/visualizer/aboutUs.html, decide/visualizer/urls.py, decide/visualizer/views.py
se ha implementado la vista about us
=> Task-091: Crear vista About Us - jossalase- Funcionalidad

decide/visualizer/templates/visualizer/contactUs.html, decide/visualizer/urls.py, decide/visualizer/views.py
toda la implementacion del contact us
=> Task-92: Crear vista Contact Us - jossalase- Funcionalidad

decide/visualizer/urls.py
Se ha añadido a la clase urls de visualizer el import necesario, concretamente el de AboutUs
=> Task-107: Corrección del import de about us - jossalase- Correcciones

decide/visualizer/templates/visualizer/visualizer.html
Corregido el fallo en la generación de los gráficos de media de edad.
=> Task-115: Fallo en la generación de gráficos por media de edad-Reyes-Correcciones

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/visualizer.html
Se ha realizado la Organización, Reestructuración y Ocultación de Gráficas.
=> Task-025: Implementación CSS

decide/visualizer/templates/visualizer/visualizer.html
Se ha vuelto a añadir el botón para enviar los resultados por Telegram
=> Task-130: Añadir botón de enviar resultados por telegram-Reyes-Correcciones

decide/visualizer/templates/visualizer/visualizer.html
Se ha añadido un botón para unirse al canal de Telegram.
=> Task-132: Añadir botón para unirse al canal de Telegram-Reyes-Funcionalidad

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/visualizer.html
Se han creado un pie de página con los enlaces para las vistas de Contact Us y About Us para facilitar el acceso, así como su css para darle consistencia.
=> Task-126-No se puede acceder a Contact Us y About Us-Vanessa-Correcciones

decide/visualizer/templates/visualizer/botResponse.html
Se ha aplicado el estilo de la página de visualización principal también a la página resultante de enviar los datos al Bot.
=> Task-131: La vista de envío correcto de los resultados de Telegram no tiene ningún estilo implementado-Pablo-Correcciones.

decide/visualizer/templates/visualizer/visualizer.html
Se ha corregido la funcionalidad de exportar los resultados a PDF
=> Task-124: No se pueden exportar los resultados a PDF - joscorfis - Correcciones

decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/views.py
Se han implementado los botones para compartir en las redes sociales
=> Task-95:Implementar botones para compartir los resultados- jossalase - Funcionalidad

decide/visualizer/tests.py
Se han implementado las pruebas de acceso a la url /visualizer/botResults/id, tanto para el id de un votación existente (status_code=200) y una no (status_code=404).
=> Task-083: Pruebas Bot de Telegram-Reyes-Prueba

decide/visualizer/templates/visualizer/aboutUs.html
Se ha arreglado el css de la vista about us añadiendo un par de parametros para que se vea bien
=> Task-120:No se muestra correctamente el CSS de la vista About U - jossalase - correcciones

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/contactUs.html
Se ha implementado un css que muestre la vista de Contact us con un aspecto consistente con el resto de vistas
=> Task-128-Modificar CSS de la vista Contact Us-Vanessa-Correcciones

decide/visualizer/templates/visualizer/visualizer.html
Gráficas de media de edad en las que se puedan apreciar las diferencias de forma más clara.
=> Task-121-Cambiar la escala del eje Y en las gráficas de edad-Vanessa-Correcciones

decide/visualizer/tests.py
se ha completado la prueba de acceso a visualizaacion
=>  Task-084: Pruebas acceso a vista de visualización de resultados-jossalase-pruebas

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/aboutUs.html
se ha corregido una barra de css que no se mostraba
=> Task-120: No se muestra correctamente el CSS de la vista About Us - jossalase - correcciones

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/visualizer.html
Se ha corregido la funcionalidad del alternar modo nocturno satisfactoriamente.
=> Task-123: Modo oscuro no funciona correctamente - joscorfis - Correcciones

decide/postproc/views.py, decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/aboutUs.html, decide/visualizer/templates/visualizer/contactUs.html, decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/tests.py
Se ha corregido el error al exportar a PDF y Excel. Se ha modificado el estilo de Visualizer, Contact Us y About Us. Las gráficas donde los candidatos no tengan votos no se muestran, se muestra un mensaje indicando que no existen datos al respecto.
=> Task-156: Fallos detectados en Visualizer-Reyes-Correcciones

decide/booth/static/booth/react/Voting/Voting.js, decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/views.py
Se ha restringido el acceso al botón para enviar los resultados de la votación por Telegram. El botón sólo se le muestra al admin. Si un usuario intenta acceder a la url del envío del mensaje del bot, se muestra un error 404 mientras no sea superuser.
=> Task-162: Restringir acceso del botón del Bot Telegram-Reyes-Correcciones

decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/views.py
Se ha corregido el error de visualización, mostrando un mensaje cuando la votacion esta en curso o no comenzada y el menu no tiene desplegables
=> Task-158: Error de visualización del menu cuando la votación no ha comenzado o esta en curso -jossalase-correcciones

decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/visualizer.html
Se ha añadido un "footer" fijo al final de la página para que subiese y bajase al hacer "scroll" en la página.
=> Task-154: Error en la visualización del "footer-Vanessa-Correcciones

decide/visualizer/static/visualizer/menu.css, decide/visualizer/static/visualizer/style.css, decide/visualizer/templates/visualizer/aboutUs.html, decide/visualizer/templates/visualizer/botResponse.html, decide/visualizer/templates/visualizer/contactUs.html, decide/visualizer/templates/visualizer/menu.html, decide/visualizer/templates/visualizer/visualizer.html
Actualización del nuevo mené exitosa, además se han arreglado pequeños fallos en otras funcionalidades.
=> Task-157: Actualizar el menu de visualizer a la nueva versión - Pablo - Correcciones

decide/visualizer/templates/visualizer/menu.html, decide/visualizer/templates/visualizer/visualizer.html
Se ha eliminado los botones del menú cuando no correspondían.
=> Task-157: Actualizar el menu de visualizer a la nueva versión-Vanessa-Correcciones

decide/visualizer/tests.py
Se han corregido los errores en las pruebas producidos por el mergeo con el resto de grupos.
=> Task-086: Pruebas exportar a PDF-Reyes-Correcciones

decide/visualizer/tests.py
Se han implementado los test de carga de acceso a la vista About Us.
=> Task-171: Pruebas de carga de vista About Us-Vanessa-Prueba

decide/visualizer/tests.py
Se han añadido las pruebas de carga de la vista del Contact Us
=> Task-177: Pruebas de carga de vista de Contact Us - Pablo - Prueba

decide/visualizer/tests.py
Se han creado los tests de los gráficos de sectores: curso y sexo.
=> Task-175: Pruebas de gráficas de sectores - Vanessa - Prueba

decide/visualizer/tests.py
Se han diseñado varias pruebas que comprueben que existe la vista del About Us y sus elementos.
=> Task-181: Prueba de entrar en About us y botones - Vanessa - Prueba

decide/visualizer/tests.py
Se han importado las pruebas que comprueban la existencia de las distintas tablas de resultados.
=>  Task-182: Pruebas de navegación en Tablas de Resultados - joscorfis - Prueba

decide/visualizer/tests.py
Se ha realizado el diagrama de sectores faltante y se ha cambiado el que ya existía a como debía aparecer.
=> Task-175: Pruebas de gráficas de sectores - Vanessa -Correciones

decide/visualizer/tests.py
se ha realizado un test para el modo oscuro y otro para el modo claro
=> Task-085:Pruebas modo oscuro-jossalase-pruebas

decide/visualizer/tests.py
Se ha implementado una prueba de la funcionalidad del botón que redirecciona al grupo de telegram donde se compartiran los resultados.
=> Task-183: Prueba de navegación en botón de entrar en el chat de telegram - joscorfis - Prueba

decide/visualizer/tests.py
se ha desarrollado las pruebas para todas las tablas menos para la tabla de delegación de alumno ya que no se ha implementado aun el tally, las pruebas estan comentadas
=> Task-188: Pruebas Tablas de Estadísticas -jossalase-pruebas

decide/visualizer/tests.py
Se han implementado las pruebas de funcionalidad de los botones que redireccionan a las distintas redes sociales donde se compartiran los resultados.
=> Task-184: Pruebas de navegación al compartir por redes sociales (whatsapp, telegram, twitter) - joscorfis - Prueba

decide/visualizer/tests.py
Se han completado todas las pruebas satisfactoriamente.
=> Task-186: Pruebas Selenium de gráficas de barras y Contact Us - Pablo - Prueba

decide/census/tests.py, decide/store/tests.py, decide/test-scripts/test-decrypt.py, decide/test-scripts/test-encrypt.py, decide/visualizer/tests.py, decide/voting/tests.py
se han comentado los test que daban fallo con travis
=> Task-160: Error de Travis - jossalase - correcciones

decide/visualizer/tests.py, decide/voting/models.py
Se han implementado tres pruebas, una para cada botón, probando que muestren y oculten de forma correcta las secciones que le corresponden a cada uno
=> Task-189: Pruebas de Botones para mostrar / ocultar las secciones-Fernando-Pruebas

decide/visualizer/tests.py
Se han implementado dos pruebas que verifican la correcta funcionalidad del botón del administrador para compartir a través del bot de Telegram los resultados de la votación.
=> Task-203: Pruebas de interfaz del botón de compartir en el bot de Telegram-Fernando-Pruebas

decide/visualizer/loadtest/locustfile.py
Se ha añadido y comprobado el funcionamiento del fichero "locust.py" satisfactoriamente
=> Task-205: Pruebas de carga Locust Visualizer - Pablo - Prueba

decide/F_local_settings.py, decide/visualizer/base_tests.py, decide/visualizer/templates/visualizer/contactUs.html, decide/visualizer/templates/visualizer/visualizer.html, decide/visualizer/tests.py, decide/visualizer/views.py, docker/Dockerfile, docker/docker-compose.yml
Configuración del script de despliegue con Docker
=> Task-209: Configurar script de despliegue con Docker-Fernando-Funcionalidad

.travis.yml
Se ha realizado el cambio de la rama que se despliega en Heroku mediante la automatización de Travis.
=> Task-215: Corrección de la automotización del despliegue de Travis - Vanessa - Correcciones

decide/visualizer/templates/visualizer/menu.html
Se ha corregido el tamaño erróneo del título "Decide" en el menú de navegación de Visualizer.
=> Task-214: Modificar el título "Decide" - joscorfis - Correcciones

decide/visualizer/templates/visualizer/aboutUs.html
Correcciones Se ha modificado la vista de About Us para que aparezcan las tablas de los diferentes equipos en la misma línea
=> Task-217: Vista errónea de las tablas de los equipos - joscorfis - correciones
